### PR TITLE
feat: update to new sdk

### PR DESCRIPTION
**Pull request by frarees**

### CODE REVIEW

**Review by eriksvedang — APPROVED** [review]
Looks great!

**Comment by eriksvedang** [comment]
@frarees What's the reason for the change of default port? Not that 32001 is bad, but there has been a lot of confusion around which one we say is the default one in the docs.

**Comment by frarees** [comment]
@eriksvedang tried to go with the default one (the one the docs say is the default one). But ofc, we can go with the default port we want. And it's also easy to change (needs to happen in the sdk now, unless the project overrides the values in the interface prefab).

**Comment by eriksvedang** [comment]
OK, I see. I opened an issue for it.

The script that comes with this project (in `bin`) starts the replication server on 12345 still.

**Comment by frarees** [comment]
@eriksvedang oh right. The bin folder wasn't updated to point to the correct tools. This is something I have to mention / document (along other changes, specially editor ones). Baking schemas and starting replication servers can be done from within Unity now:

Screenshot 2020-11-09 at 11 09 48

Starting a replication server is still a work in progress, since we need much more "power" here. So best way is to copy the run command to the clipboard (first button), and paste that in a terminal.

**Comment by eriksvedang** [comment]
@frarees I can't see this button...

**Pull request merged**
